// frontend/app/activity/page.tsx
'use client'

import { useEffect, useState } from 'react'
import { readActivity, describe, type Entry } from '@/lib/activity'
import { formatNim } from '@/lib/units'
import { shortHash } from '@/lib/nimiq'
import { locale } from '@/lib/i18n'

export default function ActivityPage() {
  const [entries, setEntries] = useState<Entry[]>([])
  const [loaded, setLoaded] = useState(false)

  useEffect(() => {
    setEntries(readActivity())
    setLoaded(true)
  }, [])

  return (
    <div className="screen">
      <header className="greeting">
        <div>
          <p className="hello">History</p>
          <p className="sub">Every move you have made</p>
        </div>
      </header>

      {entries.length ? (
        <>
          <div className="list">
            {entries.map((e) => (
              <div className="card item" key={e.txHash}>
                <div>
                  <p className="item-title">{describe(e.kind)}</p>
                  <p className="item-time tabular">
                    {when(e.at)} / {shortHash(e.txHash)}
                  </p>
                </div>
                {e.amountLuna > 0 && (
                  <span className="item-amt tabular">{formatNim(e.amountLuna, locale)}</span>
                )}
              </div>
            ))}
          </div>
          <p className="footnote">
            Recorded on this device when a transaction hash came back. Each one is real and
            verifiable on chain.
          </p>
        </>
      ) : loaded ? (
        <div className="card empty">
          <p>
            Nothing yet. When you put NIM to work or free some up, it appears here with its
            transaction hash.
          </p>
        </div>
      ) : null}
    </div>
  )
}

function when(ts: number): string {
  const s = Math.max(0, (Date.now() - ts) / 1000)
  if (s < 60) return 'just now'
  const m = Math.floor(s / 60)
  if (m < 60) return `${m}m ago`
  const h = Math.floor(m / 60)
  return h < 24 ? `${h}h ago` : `${Math.floor(h / 24)}d ago`
}

// src/routes/Activity.svelte
<script lang="ts">
  import { readActivity, describe, type Entry } from '../lib/activity'
  import { formatNim } from '../lib/units'
  import { shortHash } from '../lib/nimiq'
  import { locale } from '../lib/i18n'
  import { navigate } from '../lib/router'
  import PrimaryButton from '../components/PrimaryButton.svelte'

  let entries = $state<Entry[]>([])
  let loaded = $state(false)

  $effect(() => {
    entries = readActivity()
    loaded = true
  })

  function when(ts: number): string {
    const secs = Math.max(0, (Date.now() - ts) / 1000)
    if (secs < 60) return 'just now'
    const m = Math.floor(secs / 60)
    if (m < 60) return `${m}m ago`
    const h = Math.floor(m / 60)
    if (h < 24) return `${h}h ago`
    return `${Math.floor(h / 24)}d ago`
  }
</script>

<div class="screen">
  <header><h1>Activity</h1></header>

  {#if entries.length}
    <ol class="list">
      {#each entries as e (e.txHash)}
        <li class="row">
          <div class="left">
            <span class="what">{describe(e.kind)}</span>
            <span class="meta tabular">{when(e.at)} / {shortHash(e.txHash)}</span>
          </div>
          {#if e.amountLuna > 0}
            <span class="amt tabular">{formatNim(e.amountLuna, locale)}</span>
          {/if}
        </li>
      {/each}
    </ol>
    <p class="fine">
      Built from transactions submitted through Float on this device. Each one
      is a real transaction hash you can verify on chain.
    </p>
  {:else if loaded}
    <div class="empty">
      <p class="empty-title">Nothing yet</p>
      <p class="fine">
        When you put NIM to work or free some up, it shows here with its
        transaction hash.
      </p>
    </div>
  {/if}

  <div class="spacer"></div>

  <div class="dock">
    <PrimaryButton label="Go to balance" onclick={() => navigate('/')} />
  </div>
</div>

<style>
  header {
    padding: var(--gap-lg) 0 var(--gap-lg);
  }

  h1 {
    margin: 0;
    font-size: 28px;
    font-weight: 600;
    letter-spacing: -0.015em;
  }

  .list {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  .row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: var(--gap);
    padding: var(--gap-sm) 0;
  }

  .left {
    display: flex;
    flex-direction: column;
    gap: 2px;
    min-width: 0;
  }

  .what {
    font-size: 16px;
    font-weight: 500;
  }

  .meta {
    color: var(--muted);
    font-size: 12px;
  }

  .amt {
    color: var(--amber);
    font-size: 17px;
    font-weight: 600;
  }

  .empty {
    margin-top: var(--gap-2xl);
  }

  .empty-title {
    margin: 0 0 var(--gap-xs);
    font-size: 19px;
    font-weight: 600;
  }

  .fine {
    margin: var(--gap-lg) 0 0;
    color: var(--muted);
    font-size: 13px;
    max-width: 40ch;
  }

  .spacer {
    flex: 1;
    min-height: var(--gap-xl);
  }
</style>
