// src/routes/Validators.svelte
<script lang="ts">
  // Delegation control. Uses sendUpdateStakerTransaction, which moves an
  // existing stake to a different validator without unstaking first.
  import PrimaryButton from '../components/PrimaryButton.svelte'
  import PaymentState from './PaymentState.svelte'
  import Row from '../components/Row.svelte'
  import { readValidators, rememberValidator, addActivity } from '../lib/activity'
  import { switchValidator, readStaker } from '../lib/staking'
  import { getAddress, shortAddressSafe } from '../lib/nimiq'
  import { runTx, payment, resetPayment } from '../lib/payment'

  let recent = $state<string[]>([])
  let current = $state<string | null>(null)
  let input = $state('')
  let busy = $state(false)

  const showState = $derived($payment.status !== 'idle')
  const valid = $derived(input.trim().length >= 10)

  $effect(() => {
    recent = readValidators()
    ;(async () => {
      const a = await getAddress()
      if (!a) return
      const s = await readStaker(a)
      current = s?.delegation ?? null
    })()
  })

  async function apply() {
    if (!valid || busy) return
    busy = true
    try {
      const target = input.trim()
      await runTx(0, async () => {
        const hash = await switchValidator(target, true)
        rememberValidator(target)
        addActivity({
          txHash: hash,
          kind: 'switch',
          amountLuna: 0,
          at: Date.now(),
          validator: target,
        })
        return hash
      })
    } finally {
      busy = false
    }
  }
</script>

{#if showState}
  <PaymentState onRetry={() => {}} onDone={() => resetPayment()} />
{:else}
  <div class="screen">
    <h1 class="large-title">Validator</h1>

    <div class="group">
      <Row
        label="Delegating to"
        value={current ? shortAddressSafe(current) : 'Not yet'}
        last
      />
    </div>

    <p class="group-header">Move delegation</p>
    <div class="group">
      <Row label="New validator" last>
        {#snippet children()}
          <input class="addr" bind:value={input} placeholder="NQ..." spellcheck="false" />
        {/snippet}
      </Row>
    </div>
    <p class="footnote">
      Your stake keeps earning through the switch. Nothing is unstaked and
      nothing leaves your account.
    </p>

    {#if recent.length}
      <p class="group-header">Used before</p>
      <div class="group">
        {#each recent as v, i}
          <Row
            label={shortAddressSafe(v)}
            chevron
            last={i === recent.length - 1}
            onclick={() => (input = v)}
          />
        {/each}
      </div>
    {/if}

    <div class="spacer"></div>

    <div class="dock">
      <PrimaryButton
        label="Move delegation"
        disabled={!valid || busy}
        onclick={apply}
      />
    </div>
  </div>
{/if}

<style>
  .addr {
    width: 100%;
    min-width: 0;
    color: var(--tint);
    font-size: 17px;
    text-align: right;
    outline: none;
  }

  .spacer {
    flex: 1;
    min-height: var(--gap-xl);
  }
</style>

// frontend/app/validators/page.tsx
'use client'

// Delegation control. Uses sendUpdateStakerTransaction, which moves an
// existing stake to a different validator without unstaking first.
import { useCallback, useEffect, useState } from 'react'
import StatusScreen from '@/components/StatusScreen'
import { readValidators, rememberValidator, addActivity } from '@/lib/activity'
import { switchValidator, readStaker } from '@/lib/staking'
import { getAddress, shortAddressSafe } from '@/lib/nimiq'
import { usePayment } from '@/lib/payment'

export default function ValidatorsPage() {
  const [recent, setRecent] = useState<string[]>([])
  const [current, setCurrent] = useState<string | null>(null)
  const [input, setInput] = useState('')
  const [busy, setBusy] = useState(false)

  const state = usePayment((s) => s.state)
  const run = usePayment((s) => s.run)

  const load = useCallback(async () => {
    setRecent(readValidators())
    const a = await getAddress()
    if (!a) return
    const s = await readStaker(a)
    setCurrent(s?.delegation ?? null)
  }, [])

  useEffect(() => {
    load()
  }, [load])

  const valid = input.trim().length >= 10

  async function apply() {
    if (!valid || busy) return
    setBusy(true)
    try {
      const target = input.trim()
      await run(0, async () => {
        const hash = await switchValidator(target, true)
        rememberValidator(target)
        addActivity({
          txHash: hash,
          kind: 'switch',
          amountLuna: 0,
          at: Date.now(),
          validator: target,
        })
        return hash
      })
    } finally {
      setBusy(false)
    }
  }

  if (state.status !== 'idle') return <StatusScreen onDone={load} />

  return (
    <div className="screen">
      <header className="greeting">
        <div>
          <p className="hello">Validator</p>
          <p className="sub">Who your stake is delegated to</p>
        </div>
      </header>

      <section className="card rule">
        <div className="rule-text">
          <p className="rule-label">Delegating to</p>
          <p className="rule-sub">{current ? shortAddressSafe(current) : 'Not delegating yet'}</p>
        </div>
      </section>

      <section className="card rule">
        <div className="rule-text">
          <p className="rule-label">Move to</p>
          <p className="rule-sub">Your stake keeps earning through the switch</p>
        </div>
        <div className="rule-field wide">
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="NQ..."
            spellCheck={false}
          />
        </div>
      </section>

      {recent.length > 0 && (
        <>
          <p className="section-label">Used before</p>
          <div className="list">
            {recent.map((v) => (
              <button className="card item" key={v} onClick={() => setInput(v)}>
                <p className="item-title">{shortAddressSafe(v)}</p>
              </button>
            ))}
          </div>
        </>
      )}

      <div className="page-dock">
        <button className="cta" disabled={!valid || busy} onClick={apply}>
          Move delegation
        </button>
      </div>
    </div>
  )
}
